#lang sicp

(define (make-account balance password)
  (define ( withdraw amount)
    (if (< balance amount)
        "Недостаточно денег на счете"
        (begin (set! balance (- balance amount))
               balance)))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((count 0))
    (define (dispatch try-password m)
      (cond ((not (eq? try-password password))
             (set! count (+ count 1))
             (if (> count 7)
                 (error "Вызываем полицию!")
                 (lambda (amount) "Неверный пароль"))) 
            ((eq? m 'withdraw)
             (set! count 0)
             withdraw)
            ((eq? m 'deposit)
             (set! count 0)
             deposit)
            (else (error "Неизвестный вызов -- MAKE-ACCOUNT" m))))
    dispatch))

;;; Test
(define acc (make-account 100 'password))

((acc 'password 'withdraw) 20 )
((acc 'no-password 'withdraw) 30)
((acc 'password 'deposit) 30)
((acc 'no-password 'deposit) 100)
((acc '1234 'withdraw) 100)
((acc '2134 'withdraw) 100)
((acc '2143 'withdraw) 100)
((acc '2314 'withdraw) 100)
((acc '2341 'withdraw) 100)
((acc '2431 'withdraw) 100)
((acc '3124 'withdraw) 100)
((acc '3142 'withdraw) 100)
((acc 'password 'withdraw) 100)
